import allure
from .test_base import TestBase


@allure.feature("Checkout")
class TestSuiteCheckout(TestBase):

    @allure.story("Proceso de Checkout")
    @allure.tag('Test Case: 14')
    @allure.title("Place Order: Register while Checkout")
    def test_registro_durante_checkout_ordenar_envio(self):
        self.page_home.abrir_pagina()
        self.page_home.pagina_abierta()
        self.page_home.click_boton_products()
        self.page_productos.pagina_abierta()
        self.page_productos.add_product_to_cart_by_name('Blue Top')
        self.page_productos.click_boton_view_cart()
        self.page_carrito.pagina_abierta()
        self.page_carrito.productos_presentes_carrito('Blue Top')
        self.page_carrito.click_boton_proceed()
        self.page_carrito.click_boton_log_reg()
        self.page_login_registro.pagina_abierta()
        self.page_login_registro.introducir_nombre_registro()
        self.page_login_registro.introducir_email_registro()
        self.page_login_registro.click_boton_registro()
        self.page_registro.pagina_abierta()
        self.page_registro.rellenar_account_info()
        self.page_registro.rellenar_adress_info()
        self.page_registro.click_boton_crear_cuenta()
        self.page_cuenta_creada.pagina_abierta()
        self.page_cuenta_creada.mensaje_cuenta_creada_visible()
        self.page_cuenta_creada.click_boton_continue()
        self.page_home.pagina_abierta()
        self.page_home.user_name_visible()
        self.page_home.user_status_ok()
        self.page_home.click_boton_cart()
        self.page_carrito.pagina_abierta()
        self.page_carrito.productos_presentes_carrito('Blue Top')
        self.page_carrito.click_boton_proceed()
        self.page_checkout.pagina_abierta()
        self.page_checkout.direccion_envio_visible()
        self.page_checkout.direccion_facturacion_visible()
        self.page_checkout.verificar_info_envio()
        self.page_checkout.verificar_info_facturacion()
        self.page_checkout.rellenar_comentarios_envio()
        self.page_checkout.click_boton_place_order()
        self.page_pago.formulario_tarjeta_visible()
        self.page_pago.rellenar_formulario_tarjeta()
        self.page_pago.click_boton_confirm_order()
        self.page_envio.mensaje_pedido_realizado_visible()
        self.page_envio.click_boton_continue()
        self.page_home.pagina_abierta()

        self.borrar_cuenta()

    @allure.story("Proceso de Checkout")
    @allure.tag('Test Case: 15')
    @allure.title("Place Order: Register before Checkout")
    def test_registro_anterior_checkout_ordenar_envio(self):
        self.registrar_cuenta()

        self.page_home.click_boton_products()
        self.page_productos.pagina_abierta()
        self.page_productos.add_product_to_cart_by_name('Frozen Tops For Kids')
        self.page_productos.click_boton_view_cart()
        self.page_carrito.pagina_abierta()
        self.page_carrito.productos_presentes_carrito('Frozen Tops For Kids')
        self.page_carrito.click_boton_proceed()
        self.page_checkout.pagina_abierta()
        self.page_checkout.direccion_envio_visible()
        self.page_checkout.direccion_facturacion_visible()
        self.page_checkout.verificar_info_envio()
        self.page_checkout.verificar_info_facturacion()
        self.page_checkout.rellenar_comentarios_envio()
        self.page_checkout.click_boton_place_order()
        self.page_pago.formulario_tarjeta_visible()
        self.page_pago.rellenar_formulario_tarjeta()
        self.page_pago.click_boton_confirm_order()
        self.page_envio.mensaje_pedido_realizado_visible()
        self.page_envio.click_boton_continue()
        self.page_home.pagina_abierta()

        self.borrar_cuenta()

    @allure.story("Proceso de Checkout")
    @allure.tag('Test Case: 16')
    @allure.title("Place Order: Login before Checkout")
    def test_login_anterior_checkout_ordenar_envio(self):
        self.registrar_cuenta()
        self.logout_cuenta()
        self.login_cuenta()

        self.page_home.click_boton_products()
        self.page_productos.pagina_abierta()
        self.page_productos.add_product_to_cart_by_name('Premium Polo T-Shirts')
        self.page_productos.click_boton_view_cart()
        self.page_carrito.pagina_abierta()
        self.page_carrito.productos_presentes_carrito('Premium Polo T-Shirts')
        self.page_carrito.click_boton_proceed()
        self.page_checkout.pagina_abierta()
        self.page_checkout.direccion_envio_visible()
        self.page_checkout.direccion_facturacion_visible()
        self.page_checkout.verificar_info_envio()
        self.page_checkout.verificar_info_facturacion()
        self.page_checkout.rellenar_comentarios_envio()
        self.page_checkout.click_boton_place_order()
        self.page_pago.formulario_tarjeta_visible()
        self.page_pago.rellenar_formulario_tarjeta()
        self.page_pago.click_boton_confirm_order()
        self.page_envio.mensaje_pedido_realizado_visible()
        self.page_envio.click_boton_continue()
        self.page_home.pagina_abierta()

        self.borrar_cuenta()